version: '3'
services:
  # worker:
  #   image: ghcr.io/bxia68/llm_kg_generator:latest
  #   env_file:
  #     .env
  manager:
    image: job_manager
    build: .
    ports:
      - 8000:8000
    env_file:
      .env
    # network_mode: host